<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{445c6c3e-5f54-4453-b203-c04c9319e6f6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter_x : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter_x := counter_x + 1; ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>